[package]
name = "rabe_YCT14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rabe = "0.3.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_yct14"
harness = false
